### ISSUE TITLE
Timeout can be great or equal than the check periods

### ISSUE THREAD

**Issue by ghost** [ertek/impacto_estrategico#1]
When configuring a URL the timeout can be set to an equal or greater value than the checking periods, this causes a misbehavior since the response can expire before actually getting a response or two checks can overlap.

Observed results from this configuration:

```
"1504621599.435188","DOWN","https://www.google.com"
"1504621600.404135","UP","https://reddit.com"
"1504621602.016891","UP","https://reddit.com"
"1504621604.457372","DOWN","https://reddit.com"
"1504621604.579399","DOWN","https://www.google.com"
"1504621606.0614","UP","https://reddit.com"
"1504621607.824633","UP","https://reddit.com"
"1504621609.450376","UP","https://reddit.com"
"1504621609.7376","DOWN","https://www.google.com"
"1504621611.198449","UP","https://reddit.com"
"1504621613.002369","UP","https://reddit.com"
"1504621614.869807","UP","https://reddit.com"
"1504621614.891808","DOWN","https://www.google.com"
```
**`"1504621604.457372","DOWN","https://reddit.com"`** we got a response for the previous check but this timed out

Timeout can even be set to negative numbers; this results in checks not being made

**Comment by jorgecedi** [comment]
Thank you Ramón, I'm already on it. Can you please run the monitor in verbose mode and paste the output here?

**`python monitor.py verbose`**

 Also can you paste your configuration for reddit and google? 

I'm pushing the changes to the model in the next commit, I am changing _IntegerField_ to _PositiveIntegerField_.

Thanks.

**Comment by ghost** [comment]
reddit: timeout = 1 frecuencia = 1
google: timeout = 5 frecuencia = 5
```
2	1504633903.53	DOWN	0.0		https://www.google.com
3	1504633905.34	UP	0.7678		https://reddit.com
3	1504633907.6	DOWN	0.0		https://reddit.com
2	1504633908.68	DOWN	0.0		https://www.google.com
3	1504633909.69	UP	0.66416		https://reddit.com
3	1504633911.49	UP	0.50163		https://reddit.com
3	1504633913.6	UP	0.57358		https://reddit.com
2	1504633914.27	DOWN	0.0		https://www.google.com
```

Negative values output:
reddit: timeout = -1 frecuencia 1
google: timeout = 5 frecuencia = 5
```
(venv) [rfierro@localhost impacto_estrategico]$ python monitor.py verbose
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "monitor.py", line 101, in check_site
    r = requests.get(self.url, timeout=self.timeout, headers=DEFAULT_HEADERS)
  File "/home/rfierro/impacto_estrategico/venv/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/rfierro/impacto_estrategico/venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/rfierro/impacto_estrategico/venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rfierro/impacto_estrategico/venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/rfierro/impacto_estrategico/venv/lib/python2.7/site-packages/requests/adapters.py", line 426, in send
    timeout = TimeoutSauce(connect=timeout, read=timeout)
  File "/home/rfierro/impacto_estrategico/venv/lib/python2.7/site-packages/urllib3/util/timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/home/rfierro/impacto_estrategico/venv/lib/python2.7/site-packages/urllib3/util/timeout.py", line 133, in _validate_timeout
    "than or equal to 0." % (name, value))
ValueError: Attempted to set connect timeout to -1, but the timeout cannot be set to a value less than or equal to 0.
```
